# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(563, 263)
        self.LabelNama = QtWidgets.QLabel(Form)
        self.LabelNama.setGeometry(QtCore.QRect(170, 30, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.LabelNama.setFont(font)
        self.LabelNama.setObjectName("LabelNama")
        self.NameEdit = QtWidgets.QLineEdit(Form)
        self.NameEdit.setGeometry(QtCore.QRect(140, 70, 271, 20))
        self.NameEdit.setObjectName("NameEdit")
        self.halo = QtWidgets.QPushButton(Form)
        self.halo.setGeometry(QtCore.QRect(190, 100, 75, 23))
        self.halo.setObjectName("halo")
        self.clear = QtWidgets.QPushButton(Form)
        self.clear.setGeometry(QtCore.QRect(290, 100, 75, 23))
        self.clear.setObjectName("clear")
        self.exit = QtWidgets.QPushButton(Form)
        self.exit.setGeometry(QtCore.QRect(240, 140, 75, 23))
        self.exit.setObjectName("exit")

        self.retranslateUi(Form)
        self.exit.clicked.connect(Form.close)
        self.clear.clicked.connect(self.NameEdit.clear)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.LabelNama.setText(_translate("Form", "Masukkan Nama Anda :"))
        self.halo.setText(_translate("Form", "Halo"))
        self.clear.setText(_translate("Form", "Clear"))
        self.exit.setText(_translate("Form", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

class demoqtDesigner(QWidgets) :
        def __init__(self, parent = None):
            QtWidgets.__init__(self,parent)
            self.ui = Ui_Form()
            self.ui.setupUi(self)
            self.ui.halo.clicked.connect(self.haloClicked)

        def haloClicked(self):
            QMessageBox.information(self, 'Demo QtDesigner', 
            'Hallo %s, apa kabar?' %
            self.ui.NameEdit.text())


if __name__ == "__main__":
    import sys
    a = QApplication(sys.argv)
    Form = demoqtDesigner()
    Form.show()
    a.exec_()

